name: inventario_app_finish
description: "Aplicación de gestión de inventarios y productos con Flutter."

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"  # Asegúrate de que la versión del SDK sea compatible con Flutter 3.x

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  # Dependencias principales
  flutter_bloc: ^9.1.0  # Para manejar el estado con BLoC
  equatable: ^2.0.7     # Para comparar objetos de manera eficiente
  shared_preferences: ^2.2.3  # Para persistencia local
  get_it: ^8.0.3        # Para inyección de dependencias

  # Iconos de Cupertino (opcional, para diseño iOS)
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Lints para buenas prácticas de codificación
  flutter_lints: ^5.0.0

  # Dependencias para pruebas
  bloc_test: ^10.0.0    # Para pruebas unitarias del BLoC
  mockito: ^5.4.2       # Para simular dependencias en pruebas
  build_runner: ^2.4.6  # Para generar código (opcional, si se usa mockito)

# Configuración específica de Flutter
flutter:
  uses-material-design: true

  # Si necesitas agregar assets (imágenes, fuentes, etc.), descomenta las siguientes líneas:
  # assets:
  #   - assets/images/  # Ejemplo de carpeta de imágenes
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic